### ISSUE TITLE
change the quality as env 

### ISSUE THREAD

**Issue by x3r4n0** [Stefomat/twitch-stream-recorder#15]
i like your script! but how i can change the quality to "audio_only" ?

**Comment by Stefomat** [comment]
Unfortunately, there is no way to set this yet. The upstream twitch-recorder.py allows to set the quality individually with the option -q, but my Docker container does not use this. I never wanted to customize this setting myself, so this feature doesn't exist yet. The fastest way would be a fork, where you put the setting you want into the python script directly. I'll leave the issue open, maybe I'll add this option as an ENV variable.

**Comment by Stefomat** [comment]
I have finally implemented this feature. You can now control the [STREAM](https://streamlink.github.io/cli.html#cmdoption-arg-STREAM) setting of streamlink with the QUALITY environment variable.
